"""Ports — the narrow interfaces the engine depends on (hexagonal architecture).

The engine loop talks to the outside world only through these Protocols, never to
ccxt / postgres / the wall clock directly. Two adapter sets implement them:

  - live  (adapters_live.py): ccxt market+broker, postgres/redis ledger, webhook sink
  - sim   (G2.2 backtest):     historical replay market, simulated-fill broker, in-memory ledger

Because the engine is written against these ports, the SAME engine code runs live
and in backtest — the backtest exercises the real engine, not a reimplementation.
Ports are domain-shaped (current_side, exposure_usd, …), so no ccxt/DB row shape
leaks into the engine; each adapter does its own translation.

Protocols are structural + runtime-free: this module imports only stdlib + the
pure `market`/`risk` types, so the engine stays unit-testable with fakes anywhere.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from .market import Candles


@runtime_checkable
class MarketData(Protocol):
    """Read-only market data (live exchange, or historical replay with a bar cursor)."""
    def ohlcv(self, symbol: str, tf: str, limit: int) -> Candles: ...
    def ticker(self, symbol: str) -> float: ...
    def funding_rate(self, symbol: str) -> float | None: ...


@runtime_checkable
class Broker(Protocol):
    """Execution + book state. Live = ccxt; sim = a fill model over the replay tape."""
    def current_side(self, symbol: str) -> str | None: ...      # 'long' | 'short' | None
    def exposure_usd(self) -> float: ...                        # total notional across the book
    def equity(self) -> float: ...                              # account equity (USDT)
    def unrealized_total(self) -> float: ...
    def capture_realized(self, symbol: str) -> float: ...       # realized PnL if symbol closes now
    def place_market(self, symbol: str, side: str, qty: float) -> dict: ...   # -> {id, status}
    def set_leverage(self, symbol: str, leverage: int) -> None: ...
    def set_stop(self, symbol: str, close_side: str, qty: float, stop_price: float) -> Any: ...
    def close(self, symbol: str) -> Any: ...
    def cancel_stops(self, symbol: str) -> None: ...


@runtime_checkable
class Clock(Protocol):
    """Time source. Live = wall clock; sim = the replay's bar time (event-driven)."""
    def now(self) -> datetime: ...


@runtime_checkable
class Ledger(Protocol):
    """The trade/audit record (the store DAO subset the engine writes/reads).

    Live = postgres/redis; sim = in-memory (fast, disposable per backtest run)."""
    def current_strategy(self, symbol: str) -> str: ...
    def set_strategy(self, symbol: str, strategy: str, reason: str, set_by: str) -> None: ...
    def record_signal(self, symbol: str, strategy: str, indicators: dict, action: str) -> None: ...
    def set_rationale(self, text: str) -> None: ...
    def get_mode(self) -> str: ...
    def set_mode(self, mode: str) -> None: ...
    def close_open_positions(self, symbol: str, realized_pnl: float | None = None) -> None: ...
    def record_order(self, symbol: str, side: str, type_: str, qty: float, price: float | None,
                     status: str, exchange_order_id: str | None, strategy: str, intent: str | None) -> None: ...
    def record_position_open(self, symbol: str, side: str, qty: float, entry: float,
                             stop: float | None, strategy: str, entry_reason: str | None) -> None: ...
    def record_risk_event(self, type_: str, detail: dict, action_taken: str) -> None: ...
    def get_last_regime(self) -> str | None: ...
    def set_last_regime(self, regime: str) -> None: ...
    def heartbeat_age(self) -> float | None: ...
    def realized_total(self) -> float: ...
    def equity_peak(self) -> float | None: ...
    def record_pnl_snapshot(self, equity: float, realized: float, unrealized: float,
                            drawdown_pct: float | None) -> None: ...


@runtime_checkable
class EventSink(Protocol):
    """Where Sunday→swarm webhook events go. Live = POST + log; sim = collect."""
    def emit(self, event: dict) -> Any: ...
